In [1]:










#controllo inizializzazione python
print("ciao")


ciao


In [12]:
#creazione di variabile che raccoglie dato lista e metodo range per generazione e print per conferma output 
lista_base=(list(range(0,11,1)))
print(lista_base)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [13]:
#creazione ciclo for con nome iteratore fittizio e print
for iter in lista_base:
    print(iter)


0
1
2
3
4
5
6
7
8
9
10


In [17]:
lista_quadri=[]

In [20]:
for quadri in lista_base:
    print(quadri**2)
    lista_quadri.append(quadri**2) 

0
1
4
9
16
25
36
49
64
81
100


In [21]:
print(lista_quadri)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [23]:
lista_2d=list(range(0,11,1))
print(lista_2d)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [24]:
lista_cubo=[]

In [34]:
for fai_questo_maledetto_cubo in lista_2d:
    print(fai_questo_maledetto_cubo**3)
    lista_cubo.append(fai_questo_maledetto_cubo**3)

0
1
8
27
64
125
216
343
512
729
1000


In [36]:
quadrati = []

numeri=list(range(1,11,1))

for n in numeri:
    quadrati.append(n**2)

print(quadrati)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [37]:
quadrati = [n**2 for n in range(11)]

print(quadrati)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [42]:
tuppa={1:'one',2:'two'}
tuppa2={3:'three',4:'four'}
lista_tuppa=[tuppa,tuppa2]
print(lista_tuppa)

[{1: 'one', 2: 'two'}, {3: 'three', 4: 'four'}]


In [43]:
import numpy as np

country= np.array(['usa', 'japan', 'uk', 'lavandonia', 'india'])
country

array(['usa', 'japan', 'uk', 'lavandonia', 'india'], dtype='<U10')

In [46]:
x=np.array([[2,3,1,0]])
x.shape

(1, 4)

In [47]:
y= np.array([[2,3,1,0],[1,1,1,1]])
y.shape

(2, 4)

In [48]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
#crea un array di uno
np.ones((20,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
#crea un array di integer del range che vogliamo
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
#array tipo float
np.arange(1,10, dtype=float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
#linspace va a tracciare dei punti intermedi nel range di numeri dati. utile per tracciamento coordinate
np.linspace(1.,4., 4)

array([1., 2., 3., 4.])

In [65]:
True 

True

In [66]:
False

False

In [76]:
età=15

if età <18:
    print('sei un pullo')
else:
    print('gigachad')
if età == 15:
    print('torna al nido')
else:
    print('enorme')

sei un pullo
torna al nido


In [100]:
età=16
patente=True

if età >= 18 and patente ==True:
    print('sei abilitato alla guida! 777')
elif età <= 17 and patente ==True:
    print ('Anfame')




Anfame


In [15]:
età= int(input('quanti anni hai?'))
patente= bool(input('Hai la patente'))
if età >= 80 or età >= 18 and patente==True:
    print('bene!!! dunque hai '+ str(età) +' anni. il prossimo anno ne avrai '+str(int(età)+1)+' e hai la patente: '+str(bool(patente)))
elif età <= 17 and patente ==True:
    print ('Anfame')





bene!!! dunque hai 80 anni. il prossimo anno ne avrai 81 e hai la patente: True


In [2]:

words = ["pera","mela","banana","pesca"]

while True:
        frutto= (input('scrivi un frutto'))
        if frutto in words:
                print('buona la frutta')
                break
        else:
                print('ritenta')
                



buona la frutta


In [40]:
vowels=["a","e","i","o","u"]

vocali=(input('Scrivi una vocale'))

while True:
    if vocali not in vowels:
        (input('Scrivi una vocale'))
        print('Devi ancora studiare!')
    else:
        print('bravo, esercitati per imparare meglio!')
        break    
    

bravo, esercitati per imparare meglio!


In [5]:
def print_tre_volte():
    print('Quanto è')
    print("bello")
    print("Cicciobello")



SyntaxError: 'return' outside function (1032837185.py, line 6)

In [58]:

add=somma (a,b,c)

def somma (a:int,b:int,c:int): #a,b sono arogmenti
    '''questa funziona somma 3 numeri da input'''
    a= int(input('primo numero'))
    b= int(input('secondo numero'))
    c= int(input('terzo numero'))
    print('questa funzione somma tre numeri:')
    risultato=a+b+c
    print('il risultato è '+str(risultato))
    return risultato


somma(a,b,c)





#y=5
#z=67
#q=23

#somma(y,z,q)



add

questa funzione somma tre numeri:
il risultato è 1089
questa funzione somma tre numeri:
il risultato è 35099


1089

In [2]:


def cerchio (a:float, b:float):
    risultato= a+b
    return risultato


    

In [3]:
cerchio(23,45)

68